# Run with:
# docker compose -f docker/compose.yml up --build
services:
  openpi_env:
    image: openpi-env
    build:
      context: ..
      dockerfile: docker/openpi.Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - ..:/app
      - ${OPENPI_DATA_HOME:-../.cache/openpi}:/openpi_assets
      - ../.cache/huggingface:/opt/.cache/huggingface
      - ../.cache/jax:/root/.cache/jax
      - /app/.venv
    environment:
      - OPENPI_DATA_HOME=/openpi_assets
      - HF_HOME=/opt/.cache/huggingface
      - IS_DOCKER=true
      - HF_TOKEN=${HF_TOKEN}

    shm_size: '16g'

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
